### ISSUE TITLE
Metal Declarations Not Found?

### ISSUE THREAD

**Issue by tparisi** [google-ar/WebARonARKit#12]
Tried to build and I'm getting this error out of the box. (Only changes I made were to modify bundle ID and my personal team for code signing.)

  Unknown type name 'CVMetalTextureCacheRef'; did you mean 'CVOpenGLESTextureCacheRef'?

Configuration:

Running XCode Version 9.0 beta 6 (9M214v)
Running iOS 11 Beta 7

**Comment by judax** [comment]
This error is shown when an emulator is selected instead of a device. Beside the Play/Stop buttons in XCode you may see a dropdown button/combo that states the name of the project (WebaRonARKit) and beside it the target to build for. Connect your device using a USB cable and try drop the list of the targets. Usually, the device should be shown as the first option on the top. Try to build again.

Do not hesitate to contact us again if you find any more issues/the problem is resolved.

Thanks for testing the project!

**Comment by tparisi** [comment]
Oh derp... that's exactly it. Anyone else running into this, make sure you're building for the actual hardware and not an emulator.

**Comment by tparisi** [comment]
Thanks @judax !!

**Comment by judax** [comment]
Anytime! We should add this to the instructions. Knowing how to use XCode
is not in the web developer playbook ;). Thanks for raising an issue!
