### ISSUE TITLE
JS access to video frame (screenshot, record, or image processing)

### ISSUE THREAD

**Issue by VioletteA** [google-ar/WebARonARKit#48]
Hi, 
I'm desperately looking for a way to record the camera feed (or even just take pictures). 
Usual screenshot methods obviously don't work because camera is not rendered in html container, and the browser does'nt seems to support GetUserMedia...  

So is there a way to access to actual video frame? 

(Really sorry for posting here if it's not the right place, and thank you for this awesome project!)

**Comment by jsantell** [comment]
Are you looking for access to the video frame data in JavaScript, or looking to record a video of the entire experience for sharing on social media, etc.?

There are two rough proposals for handling AR camera access on the web: 1) where the user agent renders the camera behind content, preventing JavaScript from accessing the contents, but not requiring user permission to access the camera, and 2) providing a pixel buffer to JavaScript so that a developer can render it how they'd like, perform post-processing etc., but require permission from the user due to privacy reasons.

Due to technical reasons, WebARonARKit's implementation uses (1) and WebARonARCore currently uses (2). Using [three.ar.js](https://github.com/google-ar/three.ar.js), the `ARView` component smooths out the differences so that the end result looks similar across platforms. Right now, there's no way to access the pixel data on WebARonARKit, and unlikely in the near future.

Hope this helps!

**Comment by VioletteA** [comment]
Thank you very much for your answer, (even if it's a little disappointing! ;).
Actually, I mainly want to access to the video frame for positioning pictures in space like this screenshot, where red planes should be pictures taken. I also need to download them but not necessary in real time. 

![screenshot_20180126-194825](https://user-images.githubusercontent.com/21361485/35455555-95e0758c-02d2-11e8-95df-6e34acab2b0e.png)

I've seen that Safari now support webRTC, do you think it would be possible on WebARonARKit in a near future?

**Comment by jsantell** [comment]
Unfortunately, you'd need the ARCore implementation on Android to do something similar, where you'd have access to the pixel data. Due to how WebARonARKit is constructed, we don't have ways of exposing that information. WebRTC cannot run alongside of ARKit as they're both competing for the camera resource.

**Comment by judax** [comment]
Additionally getUserMedia does not work on the iOS WebView even on iOS 11 (at least not in the current versions and I guess 1.5 won't change that either). It works on Safari but not on the WebView :(

There is a way to expose the camera frame but is quite "complex" as it requires the frame to be converted into a Base64 string. If you are down to try it out we can provide some pointers on how to add it (it should be optional as it slows down the performance).

**Comment by judax** [comment]
You should be able to do this on WebARonARCore as the camera frame is exposed to WebGL and thus, you could render it to a canvas and use it as a texture. 

For the specific use case you mention, as having the frame in real time is not crucial (don't need it per frame in the raf loop) I think you should be able to pass the 100% resolution image (it will slow down the whole app while the passing of the information is done but it could work in theory.

**Comment by VioletteA** [comment]
As much as possible I would prefer to stay on WebARonARKit, so if there is a way to expose the camera 
frame, i'll try even if it's complex and slower... Would you mind to explain to me how I could do that?

I would have liked to do it on WebARonARCore but there are few compatible devices and I have none of them so far (and I'm waiting for the next Nexus). Nevertheless the possibility of accessing the frames through a canvas seems infinitely more convenient.

Anyway, thanks again!

**Comment by sniejadlik** [comment]
Hello, I am currently working on the hackathon using WebAROnARCore build and trying to figure out how to get the raw camera feed in real time.  When I call renderer.domElement.ToDataURL("image/png") it causes a significant delay in the application and does not allow me to access the frames continuously.  Is there anything I can do to speed that up?  How does the marker tracking work so smoothly in comparison?  Thanks for any help.

**Comment by judax** [comment]
Just submitted these PRs that address this issue in case you are interested in checking them out: 
https://github.com/google-ar/WebARonARKit/pull/53 and https://github.com/google-ar/three.ar.js/pull/100

**Comment by judax** [comment]
The PRs have landed. Please, review them. Some improvements might come in the future, like multithreading handling of the image conversion to base64, but for now, this approach seems to at least work.

**Comment by VioletteA** [comment]
Awesome work, thank you! 
Exactly what I needed :-)
